name: 🚀 Java CI/CD Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: student-crud
  JAVA_VERSION: 17
  MYSQL_CONNECT_STRING: ${{ secrets.MYSQL_CONNECT_STRING }}
  MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

jobs:
  build:
    name: 🏗️ Build & Validation
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Retrieve Code From Repo
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0

      - name: 🛠 Install Java 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: 🔐 Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create application container image
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            jecesariodev/generation-challenge:latest
            jecesariodev/generation-challenge:v${{ github.run_number }}

  deploy-dev:
    name: 🚀 Deploy DEV
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy in Azure Web App
        uses: Azure/webapps-deploy@v2.2.10
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: jecesariodev/generation-challenge:v${{ github.run_number }}
